### ISSUE TITLE
ReferenceError: isLogged is not defined

### ISSUE THREAD

**Issue by abalhier** [jrakotoharisoa/remix-workshop#2]
Il manque la déclaration d'isLogged ou il faut virer la variable :)
Ça pose problème dès l'étape ma-premiere-page.

https://github.com/jrakotoharisoa/remix-workshop/blob/743217d458ee0331bd3b73197642eff9e00d7d90/app/routes/_layout.tsx#L25

**Comment by ooga** [comment]
Fixed with 7a4130a
